services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser        # Set the PostgreSQL user
      POSTGRES_PASSWORD: mypassword # Set the PostgreSQL password
      POSTGRES_DB: mydatabase       # Name of the default database
    ports:
      - '5434:5432'